name: docker
on:
  push:
    branches:
      - "development"
      - "main"

env:
  BOOKSTACK_TAG: "24.12.1"

jobs:
  build-and-push:
    name: Build & Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:${{ vars.QEMU_TAG || 'latest' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push latest stage version
        uses: docker/build-push-action@v6
        if: github.ref == 'refs/heads/development'
        with:
          context: ./
          file: ./Dockerfile
          build-args: |
            BOOKSTACK_TAG=${{ env.BOOKSTACK_TAG }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}:latest-stage
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_REPOSITORY }}:latest-stage
          cache-to: type=inline

      - name: Build and push latest prod & tagged versions
        uses: docker/build-push-action@v6
        if: github.ref == 'refs/heads/main'
        with:
          context: ./
          file: ./Dockerfile
          build-args: |
            BOOKSTACK_TAG=${{ env.BOOKSTACK_TAG }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_REPOSITORY }}:latest
            ${{ secrets.DOCKERHUB_REPOSITORY }}:${{ env.BOOKSTACK_TAG }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_REPOSITORY }}:latest
          cache-to: type=inline

  update-description:
    name: Update description
    runs-on: ubuntu-latest
    needs: [build-and-push]
    if: success()
    continue-on-error: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_REPOSITORY }}
